<a href="https://colab.research.google.com/github/Margo-s-M/AI_Colab/blob/main/ht2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [6]:
#t1
x =np.array(range(1,12+1))
x = np.arange(1,12+1)# the same
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
x.shape

(12,)

In [8]:
x.dtype

dtype('int64')

In [12]:
#t2
new_x = x.reshape((3,4))
new_x = x.reshape((-1,4))#рахує кількість рядків
new_x.astype(np.float32)




array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]], dtype=float32)

In [18]:
#t3

x = np.zeros((8,8), dtype= np.int8)
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [20]:
x = np.zeros((8,8), dtype= np.int8)
x[1,2]=1
x


array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [22]:
x = np.zeros((8,8), dtype= np.int8)
x[2]=1
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [24]:
x = np.zeros((8,8), dtype= np.int8)
x [:,1]=1
x

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [27]:
x = np.zeros((8,8), dtype= np.int8)
x [1:4,:]=1
x

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [28]:
#4
x =np.random.randint(1,10,size=(4,3))
x

array([[9, 6, 3],
       [6, 4, 1],
       [2, 2, 1],
       [7, 3, 8]])

In [29]:
mean =np.mean(x)
mean = x.mean()
mean

4.333333333333333

In [30]:
x < mean

array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [33]:
x[x < mean] = -1
x

array([[ 9,  6, -1],
       [ 6, -1, -1],
       [-1, -1, -1],
       [ 7, -1,  8]])

In [36]:
#5
x =np.random.randint(1,10,size=(4,3))
x
x.sum()
np.sum(x)

68

In [35]:
x.sum(axis=1)


array([12, 25,  9, 15])

In [37]:
x.sum(axis=0)

array([24, 18, 26])

In [41]:
#t6
max_row = x.max(axis=1,keepdims=True)
x - max_row


array([[ 0,  0, -2],
       [-1, -3,  0],
       [-3, -2,  0],
       [ 0, -5,  0]])

In [42]:
max_row - x

array([[0, 0, 2],
       [1, 3, 0],
       [3, 2, 0],
       [0, 5, 0]])

In [43]:
#t7
x = np.random.randint(0,10, size=(4,3))
x


array([[3, 8, 3],
       [5, 2, 3],
       [1, 3, 4],
       [4, 5, 6]])

In [44]:
x.min(axis=0)

array([1, 2, 3])

In [45]:
x.argmin(axis=0)

array([2, 1, 0])