<a href="https://colab.research.google.com/github/Margo-s-M/AI_Colab/blob/main/practice22_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 1
b = 2
print(a+b)


3


In [ ]:
text = "Hello world"
print(len(text))

11


In [ ]:
print(a,b)

1 2


Попереду дуже багато цікаваго.

Перше заняття з ШІ 22.01.2025


27.01.2025  numpy


In [2]:
import numpy as np



a = np.array([1,2,3])
print(type(a)), a.shape , a[0],a[1],a[2]
a[1] *=2
print(a)

<class 'numpy.ndarray'>
[1 4 3]


Масив-  numpy — це сітка однотипних значень. Кожен елемент індексується декількома числами, в залежності від розмірності масиву.

In [ ]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.random.random(3)

array([0.56445392, 0.70697092, 0.53455116])

In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
a=b[0:2, 1:3]
print()
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[2 3]
 [6 7]]


In [ ]:
x= np.array([[-1,2],[3,4]],dtype=np.float64)
y= np.array([[5,6],[0,8]], dtype=np.float64)
print(x+y)
print(np.add(x,y))

[[ 4.  8.]
 [ 3. 12.]]
[[ 4.  8.]
 [ 3. 12.]]


In [ ]:
x

array([[-1.,  2.],
       [ 3.,  4.]])

In [ ]:
y

array([[5., 6.],
       [0., 8.]])

In [ ]:
x+y

array([[ 4.,  8.],
       [ 3., 12.]])

In [5]:
x = np.random.randint(0,10, size=(4,3))
x

array([[5, 2, 1],
       [6, 5, 8],
       [7, 4, 4],
       [5, 7, 6]])

In [7]:
x.max(axis=1)

array([5, 8, 7, 7])

In [11]:
x.max(axis=0)

array([7, 7, 8])

In [13]:
x.min(axis=0)

array([5, 2, 1])

In [14]:
x.argmin(axis=0)

array([0, 0, 0])

In [18]:
x

array([[5, 2, 1],
       [6, 5, 8],
       [7, 4, 4],
       [5, 7, 6]])

In [19]:
x.mean(axis=1)

array([2.66666667, 6.33333333, 5.        , 6.        ])

In [21]:
col_sum = x.sum(axis=0)
col_sum
x / col_sum

array([[0.2173913 , 0.11111111, 0.05263158],
       [0.26086957, 0.27777778, 0.42105263],
       [0.30434783, 0.22222222, 0.21052632],
       [0.2173913 , 0.38888889, 0.31578947]])

In [22]:
row_sum = x.sum(axis=1, keepdims=True)
x / row_sum

array([[0.625     , 0.25      , 0.125     ],
       [0.31578947, 0.26315789, 0.42105263],
       [0.46666667, 0.26666667, 0.26666667],
       [0.27777778, 0.38888889, 0.33333333]])

In [23]:
row_sum.shape

(4, 1)

In [25]:
row_sum

array([[ 8],
       [19],
       [15],
       [18]])

In [24]:
x.sum(axis=1, keepdims= False)

array([ 8, 19, 15, 18])