<a href="https://colab.research.google.com/github/Margo-s-M/AI_Colab/blob/main/%D0%A1%D0%BE%D0%B1%D1%87%D0%B5%D0%BD%D0%BA%D0%BE__%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [4]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [5]:
even_num = np.arange(30,70,2)
print(even_num)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію np.linspace

In [8]:
linspace_num = np.linspace(0,1,10,endpoint=False)
print(linspace_num)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

array([[0., 0., 0., 0.],
       [0., 1., 2., 0.],
       [0., 3., 4., 0.],
       [0., 0., 0., 0.]], dtype=float32)

#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [ ]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

array([ 1, -1,  3,  8,  6, -1,  7,  4])

array([ 1,  5,  3, -1, -1,  5, -1,  4])

array([-1,  5, -1,  8,  6,  5,  7, -1])

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [ ]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [11]:
x = np.random.randint(0,50, size=(4,6))
x

array([[13, 43,  4, 36, 35, 18],
       [11, 28, 49, 21, 36, 44],
       [36, 32, 23, 38, 18, 16],
       [49, 30, 13, 15, 26, 39]])

In [12]:
x.reshape(3,8)

array([[13, 43,  4, 36, 35, 18, 11, 28],
       [49, 21, 36, 44, 36, 32, 23, 38],
       [18, 16, 49, 30, 13, 15, 26, 39]])

#Завдання 9
Створіть випадкову матрицю розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [19]:
x = np.random.randint(0,50, size=(3,4))
x





array([[21, 19, 19, 47],
       [17, 15, 18, 47],
       [10,  4, 31, 25]])

In [20]:
col_mean = np.mean(x,axis=0)
col_mean

array([16.        , 12.66666667, 22.66666667, 39.66666667])

#Завдання 10
Є матриця з ймовірностями того, що зображення(рядки) належить певному класу(стовпчики). Для кожного зображення(рядка) знайдіть індекс класу(стовпчика) з найбільшою ймовірністю

In [ ]:
x = np.array([[0.2 , 0.3 , 0.23, 0.07, 0.03, 0.17],
              [0.15, 0.06, 0.21, 0.12, 0.24, 0.24],
              [0.1 , 0.21, 0.03, 0.07, 0.31, 0.28],
              [0.21, 0.24, 0.03, 0.18, 0.12, 0.21],
              [0.19, 0.25, 0.25, 0.06, 0.12, 0.12]])

array([1, 4, 4, 1, 1])

Пояснення: в першому рядку найбільша ймовірність -- 0.3 під індексом 1

в другому рядку -- 0.24 під індексом 4

в третьому рядку -- 0.31 під індексом 4

в четвертому рядку -- 0.24 під індексом 1

в п'ятому рядку -- 0.25 під індексом 1(там є ще одне 0.25, але ми беремо те що з меншим індексом)


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [23]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
log = X[np.logical_and(X >=3, X <=6)]
log

array([3, 4, 5, 6, 6, 5, 4, 3])

#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

[[9 8 2 8]
 [1 1 5 2]
 [8 4 9 7]]



array([[1.        , 1.        , 0.        , 1.        ],
       [0.        , 0.        , 0.42857143, 0.        ],
       [0.875     , 0.42857143, 1.        , 0.83333333]])